# server configuration
port: 8000

# kubernetes cluster configuration
kubernetes_target:
  type: "gke"  # or "minikube"
  kubeconfig_path: ~/.kube/config
  context_name: "gke_nuclio-466606_us-central1-a_nuclio-simple"

  # ingress configuration (for GKE)
  ingress:
    namespace: "ingress-nginx"
    service_name: "nginx-ingress-ingress-nginx-controller"

# nuclio platform configuration
nuclio:
  # default container registry (can be overridden per deployment)
  container_registry: "docker.io/husseinmohab"

  # target namespace for deployments
  namespace: "nuclio"

  # clean up existing function before deploying
  cleanup_before_deploy: true

  # platform wide defaults (minimal)
  function_defaults:
    metadata:
      labels:
        nuclio.io/project-name: "default"

# agent specific configuration
agent:
  # cache settings
  cache:
    max_size: 1000
    ttl_hours: 24

  # build settings
  build:
    timeout_seconds: 600
    max_image_size_mb: 2048

  # deployment settings
  deployment:
    max_concurrent: 5
    timeout_seconds: 300
    retry_attempts: 3

  # invocation settings
  invocation:
    timeout_seconds: 60
    retry_attempts: 3
    retry_delay_seconds: 1

# cross platform support
cross_platform:
  auto_detect_architecture: true
  base_images:
    darwin_arm64: "quay.io/nuclio/handler-builder-python-onbuild:1.13.24-arm64"
    darwin_amd64: "quay.io/nuclio/handler-builder-python-onbuild:1.13.24-amd64"
    linux_arm64: "quay.io/nuclio/handler-builder-python-onbuild:1.13.24-arm64"
    linux_amd64: "quay.io/nuclio/handler-builder-python-onbuild:1.13.24-amd64"