apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-agent
  namespace: nuclio
  labels:
    app: faas-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-agent
  template:
    metadata:
      labels:
        app: faas-agent
    spec:
      containers:
        - name: faas-agent
          image: husseinmohab/hydraa-agent:v1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: faas-agent
  namespace: nuclio
spec:
  selector:
    app: faas-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

