name: CI

on:
  push:
    branches: [ main, master, manager ]
  pull_request:
    branches: [ main, master, manager ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Your project and its dependencies (including pytest) are installed here
          pip install -e .

      - name: Run tests with pytest
        run: |
          python -m pytest -v
